name: test-coverage

on:
  push:
    branches: [master, main]
    paths: ['**.R', '**.qml', '**.js', 'tests/**', 'DESCRIPTION', 'NAMESPACE', 'renv.lock', '**.yml']
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths: ['**.R', '**.qml', '**.js', 'tests/**', 'DESCRIPTION', 'NAMESPACE', 'renv.lock', '**.yml']

jobs:
  coverage:
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    uses: jasp-stats/jasp-actions/.github/workflows/coverage.yml@master
    with:
      needs_JAGS: false
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
